#!/usr/bin/env bash
# Demo video recording script — narrates demo-run.sh output.
# Usage: bash scripts/demo-run.sh 2>&1 | bash scripts/video-narrate.sh
# Or record with: script -c "bash scripts/demo-run.sh" /tmp/demo.log
set -euo pipefail

echo "=== APPRENTICE V0.2 DEMO VIDEO SCRIPT ==="
echo ""
echo "NARRATION / ON-SCREEN TIMING"
echo "---------------------------"
echo ""
echo "[0:00-0:10] TITLE CARD"
echo "  Voice: \"Apprentice v0.2 — autonomous specialist training for Hermes agents.\""
echo "  Screen: repo README with architecture diagram"
echo ""
echo "[0:10-0:30] SCENE 1 — DIRECTORY SETUP"
echo "  Voice: \"The demo starts by creating the Apprentice state directory structure."
echo "          Every component — proxy, registry, datasets, checkpoints — lives under"
echo "          a single root with atomic file operations for crash safety.\""
echo "  Screen: demo-run.sh output steps 0-1, showing directory tree"
echo ""
echo "[0:30-1:00] SCENE 2 — DETECTION"
echo "  Voice: \"Three example conversations show a recurring pattern: extracting SKU"
echo "          and quantity pairs from unstructured order text. The detector identifies"
echo "          this as a candidate pattern and assigns it a deterministic correlation ID.\""
echo "  Screen: observer-pairs.jsonl content, pattern manifest JSON"
echo ""
echo "[1:00-1:30] SCENE 3 — DATASET BUILD"
echo "  Voice: \"Once the operator approves via Telegram (not shown here), the pipeline"
echo "          begins. dataset-builder fetches records from the observer, runs PII"
echo "          redaction, quality filtering, fuzzy dedup, and splits into 80/10/10"
echo "          train/val/test splits — all in gzipped JSONL.\""
echo "  Screen: dataset directory listing, manifest.json, train.jsonl.gz content"
echo ""
echo "[1:30-2:00] SCENE 4 — TRAINING"
echo "  Voice: \"The trainer loads the base model — Qwen2.5-1.5B through Unsloth's"
echo "          4-bit quantized variant — and fine-tunes a LoRA adapter. This demo"
echo "          simulates the training step since it runs GPU-free.\""
echo "  Screen: training_manifest.json showing base_model and duration"
echo ""
echo "[2:00-2:30] SCENE 5 — VALIDATION + PROMOTION"
echo "  Voice: \"Before a specialist goes live, it must pass a promotion gate: beat"
echo "          the base model by at least 10 percentage points on both exact-match"
echo "          and F1 score. The validator runs the baseline and specialist side-by-side,"
echo "          computes deltas, and only promotes if the gate clears.\""
echo "  Screen: registry_manifest.json with scores, promotion gate logic code"
echo ""
echo "[2:30-3:00] SCENE 6 — PROXY ROUTING + CANARY"
echo "  Voice: \"New specialists enter a canary warming phase — starting at 5% traffic."
echo "          Each shadow-sampled request is compared against the upstream provider."
echo "          Agreement above 80% auto-advances to 15%, then 25%, and so on until 100%."
echo "          If agreement drops, the specialist is demoted to broken and an alert fires.\""
echo "  Screen: canary state machine diagram, patterns.json, canary/state endpoint"
echo ""
echo "[3:00-3:30] SCENE 7 — MULTI-TENANCY + BUDGET"
echo "  Voice: \"Apprentice supports multi-tenant isolation: each tenant gets its own"
echo "          API key, rate limit, and resource quota. A monthly budget with Telegram-"
echo "          based increase flows gates cloud spending at 80%, 95%, and 100% thresholds.\""
echo "  Screen: tenant directory structure, budget.jsonl, quota.py logic"
echo ""
echo "[3:30-4:00] SCENE 8 — MONITORING + CI/CD"
echo "  Voice: \"Grafana dashboards show request rates, latency percentiles, cost savings,"
echo "          and pattern distribution. Every PR runs Go and Python tests with coverage"
echo "          gates, commitlint, CodeQL, and Dependabot.\""
echo "  Screen: Grafana dashboard preview, GitHub Actions workflow YAML"
echo ""
echo "[4:00-4:30] SCENE 9 — SERVING"
echo "  Voice: \"Finally, the proxy embeds every incoming chat message, cosine-matches"
echo "          against registered pattern centroids, and routes to the matching specialist."
echo "          Unmatched requests fall through to OpenRouter or your configured upstream.\""
echo "  Screen: curl command to proxy, full JSON response, dashboard URL"
echo ""
echo "[4:30-5:00] SCENE 10 — CLOSING"
echo "  Voice: \"Apprentice v0.2: deterministic routing, autonomous training, canary-"
echo "          gated deployment, multi-tenant budget control, and full observability."
echo "          Apache 2.0 licensed. Links in the description.\""
echo "  Screen: README with badge table, repo URL, contest entry info"
echo ""
echo "=== END SCRIPT ==="
echo ""
echo "RECORDING TIPS:"
echo "  1. Run:  bash scripts/demo-run.sh"
echo "  2. Record terminal with OBS, Peek, or asciinema"
echo "  3. Record voiceover separately, sync in editor"
echo "  4. Add chapter markers at each scene boundary"
echo "  5. Keep terminal font large (16pt+) for legibility"
echo "  6. Overlay architecture diagram at 0:08-0:15"
